### ISSUE TITLE
The ChatGPT page is not working properly.  error is displayed:

### ISSUE THREAD

**Issue by AndyLin2020** [xsigoking/chatgpt-free-api#8]
{
  "status": false,
  "error": {
    "message": "The requested endpoint was not found.",
    "type": "invalid_request_error"
  }
}

**Comment by xsigoking** [comment]
chagpt-free-api is an api server, not a website.

you may need [chatgpt-next-web](https://github.com/ChatGPTNextWeb/ChatGPT-Next-Web) to work with the api.
